# ========== Data Configuration ==========
data_dir: ./data_impressionism        
log_dir: ./logs                      
img_size: 128                       
batch_size: 64                       

# ========== Model & Training ==========
epochs: 100                           
lr: 0.0002                           
latent_dim: 128
beta: 0.5   
beta_warmup: 10
beta_cycle: 20                             
conditional: False                     

# ========== Sampling ==========
sample_every: 10                     
sample_per_class: 8                   

# ========== Inference ==========
inference: Trus                      
model_path: best_models/best_impressionism.pt
n_samples: 64                        