# ========== Data Configuration ==========
data_dir: ./data_apples         
log_dir: ./logs                      
img_size: 96                       
batch_size: 64                      

# ========== Model & Training ==========
epochs: 100                           
lr: 0.0002                           
latent_dim: 128                      
beta: 1.5                             
conditional: False                     

# ========== Sampling ==========
sample_every: 10                     
sample_per_class: 8                   

# ========== Inference ==========
inference: True                      
model_path: ./logs/vae_apples_2025-05-05_16-59-18/vae_epoch_100.pt
n_samples: 16                        