data_dir: ./data_impressionism        
log_dir: ./logs                      
img_size: 128                       
batch_size: 64                       
epochs: 100                           
lr: 0.0005                           
latent_dim: 128
beta: 0.5   
beta_warmup: 10
beta_cycle: 20                             
conditional: False                     
sample_every: 10                     
sample_per_class: 8                   
inference: false                      
n_samples: 16                        