data_dir: ./data_apples         
log_dir: ./logs                      
img_size: 96                       
batch_size: 64                      
epochs: 100                           
lr: 0.0002                           
latent_dim: 128
beta: 4.0   
beta_warmup: 10
beta_cycle: 20                             
conditional: False                     
sample_every: 10                     
sample_per_class: 8                   
inference: false                      
n_samples: 16                        