# ========== Data Configuration ==========
data_dir: ./data_impressionism         
log_dir: ./logs                      
img_size: 128                       
batch_size: 64                      

# ========== Model & Training ==========
epochs: 100                           
lr: 0.0002                           
latent_dim: 128                      
beta: 1.0                             
conditional: False                     

# ========== Sampling ==========
sample_every: 10                     
sample_per_class: 8                   

# ========== Inference ==========
inference: false                      
model_path: ./logs/vae_2025-05-05_04-22-42/vae_epoch_100.pt
n_samples: 16                        